---
- name: Install ssh key
  authorized_key:
    key: "{{ lookup('file', k3s_ssh_key) }}"
    user: pi
    state: present

- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel   ALL=(ALL:ALL) NOPASSWD:ALL'
    state: present

- name: Limit sshd password and root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
  notify:
    - Restart sshd

- name: Install required packages
  package:
    name:
      - open-iscsi
    state: present
