---
- include_tasks: "{{ task }}"
  loop:
    - precheck.yml
    - prepare.yml
    - install.yml
  loop_control:
    loop_var: task

- include_tasks: controller.yml
  when: k3s_controller

- include_tasks: worker.yml
  when: not k3s_controller
