apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/aggregated-metrics-reader.yaml
  - base/auth-delegator.yaml
  - base/auth-reader.yaml
  - base/metrics-apiservice.yaml
  - base/metrics-server-deployment.yaml
  - base/metrics-server-service.yaml
  - base/resource-reader.yaml

images:
  - name: k8s.gcr.io/metrics-server-amd64
    newName: k8s.gcr.io/metrics-server-arm
