apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: fuseim.pri/ifs
parameters:
  archiveOnDelete: "false"
mountOptions:
  - nfsvers=4
