apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - class.yaml
  - base/deployment-arm.yaml
  - base/rbac.yaml

patchesStrategicMerge:
  - patches.yaml
