kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: pi-controller.lan
            - name: NFS_PATH
              value: /var/vol/nfs/k8s/pv
      volumes:
        - name: nfs-client-root
          nfs:
            server: pi-controller.lan
            path: /var/vol/nfs/k8s/pv
