---
- name: Setup apt repos
  apt_repository:
    repo: deb http://raspbian.raspberrypi.org/raspbian/ testing main contrib non-free rpi
    state: present
  notify:
    - Update APT cache

- name: Setup default apt repo
  copy:
    dest: /etc/apt/apt.conf.d/90defaultrepo
    content: |-
      APT::Default-Release "stable";
  notify:
    - Update APT cache

- meta: flush_handlers

- include_tasks: "{{ task }}"
  loop:
    - raid.yml
    - nfs.yml
    - iscsi.yml
  loop_control:
    loop_var: task
